version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build: .
    container_name: api-swapi-ls
    ports:
      - "${PORT}:${PORT}" 
    environment:
      - NODE_ENV=production
      - SWAPI_BASE_URL=${SWAPI_BASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY=y${API_KEY:-123456}
      - PORT=${PORT:-3001} 
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
